name: Build
on: [push, pull_request]


jobs:
#   build_on_linux:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@master
#       with:
#         node-version: 14
#     - name: install dependencies
#       run: npm install
#     - name: build
#       run: npm run build

#   build_on_mac:
#     runs-on: macos-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@master
#       with:
#         node-version: 14
#     - name: install dependencies
#       run: npm install
#     - name: build
#       run: npm run build

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build-windows
    - name: prep
      run: npm run prep-windows
    - name: packager
      run: npm run electron-packager-windows
    - name: deploy
      uses: actions/upload-artifact@v2
      with:
        name: application-download
        path: .
